parameters:
    chewbacco_sitemap.generator_chain.class: Chewbacco\SitemapBundle\Services\SitemapGeneratorChain

services:
    chewbacco_sitemap.generator_chain:
        class: %chewbacco_sitemap.generator_chain.class%
        arguments: [ @router, { file_path: %kernel.root_dir%/../web/sitemaps/index.xml } ]
